### ISSUE TITLE
Prevent accidental kernel upgrades

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#496]
The lustre support matrix is at https://wiki.whamcloud.com/display/PUB/Lustre+Support+Matrix

assigned to myself

### calim compute nodes
calim nodes should probably stay with rhel 8.8 for a while. I tried and the lustre client kernel module does not compile easily under rhel 8.9. The key thing is that we want to keep the packages up-to-date somewhat so that we don't end up with wildly out-of-date gcc in a few years. Updates for rhel 8.8 stops mid 2027. Someone keep an eye on that.

### lwastor00 aka the lustre mgs/mds node
the mgs has a lustre-pactched kernel. Probably don't want to touch it unless we're upgrading the lustre server version. dnf/yum seems to be correctly configured.

### lwastor01-08 the oss nodes
They're using the RHEL kernel so are more prone to accidental upgrades. We probably don't need as much software upgrades on them though.

###TODOs
- [x] script to exclude kernel, zfs from dnf/yum upgrades on all nodes.
- [x] plan for routine software updates on calim nodes + path to rhel8.10 or rhel 9
- [x] documentation on using yum/dnf (like...`dnf update` actually upgrades everything....)

**Comment by yupinghuang** [comment]
script in the form of a ansible runbook https://github.com/ovro-lwa/ansible/blob/main/dnf-exclude.yaml
Docs https://github.com/ovro-lwa/calim-ops/wiki/9999-Admin#rule-number-one
